### ISSUE TITLE
non-latest new crate version was not rendered

### ISSUE THREAD

**Issue by bluss** [onur/docs.rs#84] opened 2016-11-25 19:58 UTC
The latest version of `ndarray` yesterday was 0.7.0.

Today I published 0.6.10 first and then 0.7.1 in quick succession (the same bugfix in both); it looks like docs.rs has only rendered 0.7.1 and not 0.6.10.

docs.rs is really great, but this is a bug if it intends to render all released versions.

**Comment by onur** [comment] 2016-11-25 21:15
Yes this is actually duplicate of #47.

Docs.rs is still showing latest published version instead of latest version. I'll try to adjust SQL query that finds recent version.

**Comment by onur** [comment] 2016-11-25 21:22
Ahh its because docs.rs is getting new crates from https://crates.io/summary

And this page only lists one version of a crate. If you release more than one version, summary will only show latest version.

Looks like detecting new crates still have some issues after all.

**Comment by bluss** [comment] 2016-11-26 15:26
Interesting, thank you! I am not sure the summary page ever displays versions that are not the greatest (not anymore). We could test that.

**Comment by nagisa** [comment] 2016-12-23 23:55
It seems to me that simply fetching crates.io index and looking at its commits is much more reliable way to figure out all updates. You could use `git2` crate for that and AFAICT would even be able to avoid checking out the repository tree – simply inspecting the diffs would do.

**Comment by onur** [comment] 2016-12-24 08:40
@nagisa I was doing [https://github.com/onur/docs.rs/blob/0dfb64c64667f5b79361bdbaae26a80546c50eb6/src/docbuilder/queue.rs](exactly that) before using crates.io/summary, but git2 crate started giving some errors, you can see it in #76. I still don't know what caused this but clearing insane `~/.cargo/registry` fixed the issue.

And I am not sure parsing diff from git crate was best way to get new crates. That is actual reason why I switched to crates.io/summary method.

**Closed** 2016-12-26 22:03 UTC
Labels: important
