### ISSUE TITLE
Exact matches not appearing at top

### ISSUE THREAD

**Issue by ticki** [onur/docs.rs#144] opened 2017-08-05 22:24 UTC
For example, [searching for seahash](https://docs.rs/releases/search?query=seahash) has fxhash as top result, but `seahash` only appears in its benchmarks. I presume it is because the last version of fxhash is newer than the last version of seahash, but it is clear that the exact matching search should take precedence over the other ones.

**Comment by onur** [comment] 2017-08-06 11:31
I think I managed to break it even more while I was trying to improve things in #111

Duplicate of #111

**Comment by ticki** [comment] 2017-08-06 11:39
Oh, this seems like a dup then.

**Comment by hobofan** [comment] 2017-08-15 23:03
I just built all the versions of the relevant crates for #111, and this issue in a local environment, and while I can reproduce the wrong ordering of `ndarray`, I can't reproduce the issue with `seahash` not being on top.

**Comment by onur** [comment] 2017-08-30 16:50
b1e2222 fixed this as well.

**Closed by onur** 2017-08-30 16:50 UTC
